/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find Total Customers by Countries
SELECT
	country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find Total Customers by Gender
SELECT
	gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find Total Products by Category
SELECT
	category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the Average Costs in each Category?
SELECT
	category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the Total Revenue generated for each Category?
SELECT
	p.category,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS fs
ON p.product_key = fs.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find the Total Revenue is generated by each Customer 
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS fs
ON c.customer_key = fs.customer_key
GROUP BY 
	c.customer_key,
    first_name,
    last_name
ORDER BY total_revenue DESC;

-- What is the Distribution of Sold Items across Countries? 
SELECT
	c.country,
    SUM(fs.sales_amount) AS total_sold_items
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS fs
ON c.customer_key = fs.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- What is the average revenue generated per customer?
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    ROUND(AVG(fs.sales_amount), 2) AS avg_revenue
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS fs
ON c.customer_key = fs.customer_key
GROUP BY 
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY avg_revenue DESC; 

-- Which country has the highest average customer spending?
SELECT 
	c.country,
    ROUND(AVG(fs.sales_amount), 2) AS avg_customer_spending
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS fs
ON c.customer_key = fs.customer_key
GROUP BY c.country
ORDER BY avg_customer_spending DESC;


-- Which customers have purchased the most products?
SELECT
	c.customer_key, 
	c.first_name,
    c.last_name,
    COUNT(fs.quantity) AS total_quantity_purchased
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS fs
ON c.customer_key = fs.customer_key
GROUP BY
	c.customer_key, 
	c.first_name,
    c.last_name
ORDER BY total_quantity_purchased DESC;
